### ISSUE TITLE
Main Control Loop

### ISSUE THREAD

**Issue by caanaan** [SouthportCybercards/CybercardsFRC#5]
The main control loop to be called periodically in teleop.

Should have default hooks into the outer arm control, inner lift control, and the drive base control.

**Comment by Gmanncool101** [comment]
Drafted in 6a36b83b69e7bd88e8f7f0c83edcbe4f182b5aa6.  Need to write control functions, include in main loop, and test.
Should be ready to close after testing on robot.

**Comment by zxsq** [comment]
2015 season is over
