### ISSUE TITLE
Inner Lift Control

### ISSUE THREAD

**Issue by caanaan** [SouthportCybercards/CybercardsFRC#6]
Open loop control of the inner lift control.

Should just move up and down based on configurable user input (probably from the d-pads on the top of the joysticks).

**Comment by caanaan** [comment]
Drafted in f36290843c804a1e2421b01315d62cd1857f4d5a.  Should be ready when tested on the robot.

**Comment by zxsq** [comment]
~~Auto/state control done. Should be tested on robot.~~
Not actually done. But closer.

**Comment by caanaan** [comment]
Doesn't look like the code was committed - make sure to do that. :)

**Comment by zxsq** [comment]
done, and the season is too.
