### ISSUE TITLE
Outer Arm Control

### ISSUE THREAD

**Issue by caanaan** [SouthportCybercards/CybercardsFRC#7]
Open loop control of the outer arms - both rotational and vertical.  Each arm should be independently controllable.

Should be based on user input - likely up and down from a joystick forward and back, and rotation from a joystick left and right.

**Comment by caanaan** [comment]
Tested on the prototype board and works, but haven't tested on the actual robot, so basically done.

**Comment by zxsq** [comment]
feature removed, season over
