### ISSUE TITLE
Drive Base Control

### ISSUE THREAD

**Issue by caanaan** [SouthportCybercards/CybercardsFRC#8]
Open loop control of the drive base.

Should accept tank style input from 2 joysticks - likely just forward and back from each.

**Comment by Gmanncool101** [comment]
Saturday - we updated the code and tested it on the proto board.  The basic drive base code should be working from commit 05cb7c995f9c68f9cc616f1eeedfe18dafe9845f.

**Comment by Gmanncool101** [comment]
Should be ready for closure after testing on the actual robot.

**Comment by caanaan** [comment]
If you have having issues with the motors being inverted, it looks like setting a motor to be inverted is done using the SetInvertedMotor function in the RobotDrive class.
See the documentation here: http://first.wpi.edu/FRC/roborio/release/docs/cpp/classRobotDrive.html

Some examples/references of other people addressing this issue: http://www.reddit.com/r/FRC/comments/1wgcio/problem_with_motor_direction/
https://github.com/rbmj/612-guillotine/blob/master/main.cpp

**Comment by zxsq** [comment]
It drives. Quite well.

**Comment by caanaan** [comment]
Sweet. :)
